export { default as AddMovie } from './AddMovie'
export { default as MovieDetails } from './MovieDetails'
export { default as Home } from './Home'
export { default as EditMovie } from './EditMovie'
export { default as Favorite } from './Favorite'